bakery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as v
from pages import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home_view, name='home'),

    path('products/', views.product_list, name='product_list'),

    path('topic/<int:topic_id>/', views.topic, name='topic'),

    path('register/', views.register_customer, name='register'),
    path('login/', v.LoginView.as_view(next_page='home'), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('cart/', views.cart, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('sub-from-cart/<int:product_id>/', views.substract_from_cart, name='sub_from_cart'),

    path('orders/', views.order_view, name='orders')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Order(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.PROTECT, null=False, blank=False, verbose_name='Заказчик')
    date_of_delivery = models.DateField(null=False, blank=False, verbose_name='Дата доставки')
    time_of_order = models.DateTimeField(null=False, blank=False, auto_now_add=True, editable=False,
                                         verbose_name='Время заказа')
    address_of_delivery = models.CharField(null=False, blank=False, max_length=128, verbose_name='Адрес доставки')
    total_price = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2,
                                      verbose_name='Итоговая стоимость')
    type_of_payment = models.ForeignKey('TypeOfPayment', on_delete=models.PROTECT, null=False, blank=False,
                                        verbose_name='Тип оплаты')
    commentary_for_order = models.TextField(null=True, blank=True, verbose_name='Комментарий к заказу')

    def __str__(self):
        return '%s %s %s' % (self.customer, self.date_of_delivery, self.total_price)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class TypeOfPayment(models.Model):
    name = models.CharField(max_length=32, verbose_name='Тип оплаты')

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = 'Типы оплаты'
        verbose_name_plural = 'Типы оплаты'


class OrderAndState(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Заказ')
    state_of_order = models.ForeignKey('StateOfOrder', on_delete=models.CASCADE, null=False, blank=False,
                                       verbose_name='Статус заказа')
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Работник')

    def __str__(self):
        return '%s %s %s' % (self.order.customer, self.state_of_order, self.employee)

    class Meta:
        verbose_name = 'Заказ и статус'
        verbose_name_plural = 'Заказы и статусы'


class StateOfOrder(models.Model):
    name = models.CharField(null=False, blank=False, max_length=32, verbose_name='Статус заказа')

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказов'


class OrderPosition(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Заказ')
    price_list_position = models.ForeignKey('PriceListPosition', on_delete=models.CASCADE, null=False, blank=False,
                                            verbose_name='Продукт')
    count_of_products = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2,
                                            verbose_name='Количество')
    price_of_position = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2,
                                            verbose_name='Стоимость позиции')

    def __str__(self):
        return '%s %s %s %s' % (self.order, self.price_list_position, self.count_of_products, self.price_of_position)

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'


class PriceList(models.Model):
    approval_date = models.DateField(null=False, blank=False, auto_now_add=True,
                                     verbose_name='Дата утверждения прайс-листа')

    def __str__(self):
        return '%s' % (self.approval_date)

    class Meta:
        verbose_name = 'Прайс-лист'
        verbose_name_plural = 'Прайс-листы'


class PriceListPosition(models.Model):
    price_list = models.ForeignKey('PriceList', on_delete=models.CASCADE, null=False, blank=False,
                                   verbose_name='Прайс-лист')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Продукт')
    price = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2, verbose_name='Цена')
    units = models.CharField(null=False, blank=False, max_length=32, verbose_name='Единица измерения')

    def __str__(self):
        return '%s %s %s' % (self.price_list, self.product, self.price)

    class Meta:
        verbose_name = 'Позиция прайс-листа'
        verbose_name_plural = 'Позиции прайс-листов'


class Product(models.Model):
    title = models.CharField(max_length=64, null=False, blank=False, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    weight = models.IntegerField(null=False, blank=False, verbose_name='Вес (гр.)')
    image = models.ImageField(null=True, blank=True, upload_to='products_img/')

    def __str__(self):
        return '%s' % (self.title)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class TagAndProduct(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Продукт')
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Тег')

    def __str__(self):
        return '%s %s' % (self.product, self.tag)

    class Meta:
        verbose_name = 'Тег и продукт'
        verbose_name_plural = 'Теги и продукты'
        unique_together = ('product', 'tag')


class Tag(models.Model):
    title = models.CharField(max_length=64, null=False, blank=False, verbose_name='Наименование для тега')
    title_for_topic = models.CharField(max_length=64, null=True, blank=True, verbose_name='Наименование')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    board_image = models.ImageField(null=True, blank=True, upload_to='tags_img/board')
    icon_image = models.ImageField(null=True, blank=True, upload_to='tags_img/icon')

    def __str__(self):
        return '%s' % (self.title)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Customer(User):
    phone_number = models.CharField(max_length=18, null=False, blank=False, verbose_name='Номер телефона')

    class Meta:
        verbose_name = 'Покупатель'
        verbose_name_plural = 'Покупатели'


class Employee(User):
    date_of_employment = models.DateField(null=False, blank=False, verbose_name='Дата приема на работу')
    date_of_dismissal = models.DateField(null=True, blank=True, verbose_name='Дата увольнения')
    employees_position = models.CharField(max_length=32, null=True, blank=True, verbose_name='Должность')

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, inital-scale=1.0">
    <title>Добрая пекарня</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body style="background: #fef4e4">
{% include 'navbar.html' with topics=topics %}
<section class="main">
    {% block content %}
    {% endblock %}
</section>
<footer class="footer">
    {% include "footer.html" %}
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
<style>
    * {
        color: #17120a;
    }

    .main {
        display: flex;
        min-height: 83vh;
        overflow-y: auto;
        padding: 1rem;
        border-top-right-radius: 2rem;
        border-top-left-radius: 2rem;
        background-color: #fcdfad;
        padding-bottom: 2rem;
    }
    .footer{
        display: flex;
        border-top-right-radius: 2rem;
        border-top-left-radius: 2rem;
        background-color: #facf84;
        margin-top: -2rem;
        padding: 2rem;
    }
    .custom-button-pill{
        border-radius: 1000px;
        background: #F9C469;
        color: #2d2413;
        font-weight: bolder;
        padding:0.3em;
    }
    .custom-button-pill:hover{
        border-radius: 1000px;
        background: #facf84;
        color: #5b4726;
        font-weight: bolder;
    }
</style>
</html>

pages/templates/cart.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Наименование</th>
                    <th scope="col">Цена за единицу</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Итог за строку</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr>
                        <th scope="row">{{ product.product.title }}</th>
                        <th>{{ product.price }} руб.</th>
                        <th>
                            <a class="btn custom-button-pill" href="{% url 'sub_from_cart' product.id %}">-</a>
                            {{ product.count }} {{ product.units }}
                            <a class="btn custom-button-pill" href="{% url 'add_to_cart' product.id %}">+</a>
                        </th>
                        <th>{% widthratio product.count 1 product.price %} руб.</th>
                    </tr>
                {% endfor %}
                <tr>
                    <th scope="row"><b>Итог</b></th>
                    <th></th>
                    <th></th>
                    <th><b>{{ total_price }} руб.</b></th>
                </tr>
                </tbody>
            </table>
        </div>
        <hr>
        <div class="row">
            <form method="post" action="">
                {% csrf_token %}
                <div class="container">
                    <div class="row roww">
                        <div class="col">
                            <label for="date_of_delivery">Дата доставки:</label>
                        </div>
                        <div class="col">
                            <input type="date" name="date_of_delivery" id="date_of_delivery" required>
                        </div>
                    </div>
                    <div class="row roww">
                        <div class="col">
                            <label for="address_of_delivery">Адрес доставки:</label>
                        </div>
                        <div class="col">
                            <input type="text" name="address_of_delivery" id="address_of_delivery" required>
                        </div>
                    </div>
                    <div class="row roww">
                        <div class="col">
                            <label for="type_of_payment">Тип оплаты:</label>
                        </div>
                        <div class="col">
                                {% for payment_type in payment_types %}
                                    <p>
                                    <input type="radio" name="type_of_payment" id="type_of_payment" value="{{ payment_type.id }}">
                                    {{ payment_type.name }}
                                    </p>
                                {% endfor %}
                        </div>
                    </div>
                    <div class="row roww">
                        <div class="col">
                            <label for="commentary_for_order">Комментарий к заказу:</label>
                        </div>
                        <div class="col">
                            <textarea name="commentary_for_order" id="commentary_for_order"></textarea>
                        </div>
                    </div>
                    <div class="row roww">
                        <button type="submit" class="btn custom-button-pill">Оформить заказ</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <style>
        .roww {
            padding: 1em 1em 1em 0em;
            margin-right: 40%;
        }
    </style>
{% endblock %}

pages/templates/footer.html
{% block content %}
    <div class="footer">
        <div>
            <a href="/" class="footer-logo-borders">Добрая пекарня</a>
        </div>
        <div class="footer-txt">
            <p><i class="bi bi-telephone"></i>+7(911)597-14-51</p>
            <p><i class="bi bi-envelope"></i>dobryaya@yandex.ru</p>
            <p><i class="bi bi-globe"></i>http://www.dobryaya.ru</p>
        </div>
        <div class="footer-txt">
            <p><i class="bi bi-code-slash"></i>Developer: ZoomBySNik</p>
            <p><i class="bi bi-brush"></i>Designer: red_dragon</p>

        </div>
    </div>
{% endblock content %}
<style>
    .footer{
        display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1em 4em;
            width: 100%;
            background: rgba(0, 0, 0, 0.05);
    }
    .footer-logo-borders{
            border-style: solid;
            border-radius: 1000px;
            border-width: 0.09em;
            padding: 0.3rem 0.3rem;
            line-height: 0.9rem;
            font-size: 1.4em;
            font-weight: 100;
            text-decoration: none;
            color: inherit;
            margin-right: 3em;
    }
    .footer-txt p{
        margin-bottom: 0em;
    }

</style>

pages/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% include 'objects/carusel.html' with topics=topics %}
        <div class="title-of-section">
            <h1 style="text-align: center">Популярные товары</h1>
        </div>
        {% include 'objects/card.html' with orders=orders %}
        <div class="title-of-section"><a href="/products"><button class="btn btn-lg custom-button-pill">Хочу видеть больше</button></a></div>
    </div>
    <style>
        .title-of-section{
            margin: 2em;
            text-align: center;
        }
    </style>
{% endblock %}

pages/templates/navbar.html
{% block content %}
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <div>
            <a class="navbar-brand" href="/">
                Добрая пекарня
            </a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Категории
          </a>
          <ul class="dropdown-menu">
              {% for item in topics %}
                    <li><a class="dropdown-item" href="{% url 'topic' item.id %}">{{ item.title_for_topic }}</a></li>
              {% endfor %}
          </ul>
        </li>
        <li class="nav-item" >
            <a class="nav-link" href="/products">
                Все меню
            </a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="/products" method="GET">
        <input class="form-control me-2" type="text" name="search" placeholder="Поиск" aria-label="Поиск">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
        {% if request.user.is_authenticated %}
            {% if orders_for_check %}
                <a class="btn btn-info" style="margin-left: 1em" href="{% url 'orders' %}">Заказы</a>
            {% endif %}
            {% if cart %}
                <a class="btn btn-info" style="margin-left: 1em" href="{% url 'cart' %}">Корзина</a>
            {% endif %}
            <a class="btn btn-info" style="margin-left: 1em" href="{% url 'logout' %}">Выход</a>
        {% else %}
            <a class="btn btn-info" style="margin-left: 1em" href="{% url 'login' %}">Вход</a>
        {% endif %}
    </div>
  </div>
</nav>
<style>
        .navbar-brand{
            background: none;
            justify-content: center;
            display: flex;
            margin: auto;
        }
    </style>
{% endblock content %}

pages/templates/orders.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h2>Ваши заказы {{ user.get_full_name }}</h2>
        {% for order in orders %}
            <div class="row">
                <h5>Заказ #{{ forloop.counter }} от {{ order.time_of_order }}</h5>
                <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Наименование</th>
                    <th scope="col">Цена за единицу</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Итог за строку</th>
                </tr>
                </thead>
                <tbody>
                {% for order_position in order.orderposition_set.all %}
                    <tr>
                        <th scope="row">{{ order_position.price_list_position.product.title }}</th>
                        <th>{{ order_position.price_list_position.price }} руб.</th>
                        <th>
                            {{ order_position.count_of_products }} {{ order_position.price_list_position.units }}
                        </th>
                        <th>{{ order_position.price_of_position }} руб.</th>
                    </tr>
                {% endfor %}
                <tr>
                    <th scope="row"><b>Итог</b></th>
                    <th></th>
                    <th></th>
                    <th><b>{{ order.total_price }} руб.</b></th>
                </tr>
                </tbody>
                </table>
            {% for order_status in order.orderandstate_set.all %}
                <p>{{ order_status.state_of_order }}</p>
            {% endfor %}
            <p>Дата доставки {{ order.date_of_delivery }}</p>
            </div>
        {% endfor %}

    <style>
        .roww {
            padding: 1em 1em 1em 0em;
            margin-right: 40%;
        }
    </style>
{% endblock %}