bakery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as v
from pages import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home_view, name='home'),

    path('products/', views.product_list, name='product_list'),

    path('topic/<int:topic_id>/', views.topic, name='topic'),

    path('register/', views.register_customer, name='register'),
    path('login/', v.LoginView.as_view(next_page='home'), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('cart/', views.cart, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('sub-from-cart/<int:product_id>/', views.substract_from_cart, name='sub_from_cart'),

    path('orders/', views.order_view, name='orders')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Order(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.PROTECT, null=False, blank=False, verbose_name='Заказчик')
    date_of_delivery = models.DateField(null=False, blank=False, verbose_name='Дата доставки')
    time_of_order = models.DateTimeField(null=False, blank=False, auto_now_add=True, editable=False,
                                         verbose_name='Время заказа')
    address_of_delivery = models.CharField(null=False, blank=False, max_length=128, verbose_name='Адрес доставки')
    total_price = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2,
                                      verbose_name='Итоговая стоимость')
    type_of_payment = models.ForeignKey('TypeOfPayment', on_delete=models.PROTECT, null=False, blank=False,
                                        verbose_name='Тип оплаты')
    commentary_for_order = models.TextField(null=True, blank=True, verbose_name='Комментарий к заказу')

    def __str__(self):
        return '%s %s %s' % (self.customer, self.date_of_delivery, self.total_price)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class TypeOfPayment(models.Model):
    name = models.CharField(max_length=32, verbose_name='Тип оплаты')

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = 'Типы оплаты'
        verbose_name_plural = 'Типы оплаты'


class OrderAndState(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Заказ')
    state_of_order = models.ForeignKey('StateOfOrder', on_delete=models.CASCADE, null=False, blank=False,
                                       verbose_name='Статус заказа')
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Работник')

    def __str__(self):
        return '%s %s %s' % (self.order.customer, self.state_of_order, self.employee)

    class Meta:
        verbose_name = 'Заказ и статус'
        verbose_name_plural = 'Заказы и статусы'


class StateOfOrder(models.Model):
    name = models.CharField(null=False, blank=False, max_length=32, verbose_name='Статус заказа')

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказов'


class OrderPosition(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Заказ')
    price_list_position = models.ForeignKey('PriceListPosition', on_delete=models.CASCADE, null=False, blank=False,
                                            verbose_name='Продукт')
    count_of_products = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2,
                                            verbose_name='Количество')
    price_of_position = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2,
                                            verbose_name='Стоимость позиции')

    def __str__(self):
        return '%s %s %s %s' % (self.order, self.price_list_position, self.count_of_products, self.price_of_position)

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'


class PriceList(models.Model):
    approval_date = models.DateField(null=False, blank=False, auto_now_add=True,
                                     verbose_name='Дата утверждения прайс-листа')

    def __str__(self):
        return '%s' % (self.approval_date)

    class Meta:
        verbose_name = 'Прайс-лист'
        verbose_name_plural = 'Прайс-листы'


class PriceListPosition(models.Model):
    price_list = models.ForeignKey('PriceList', on_delete=models.CASCADE, null=False, blank=False,
                                   verbose_name='Прайс-лист')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Продукт')
    price = models.DecimalField(null=False, blank=False, max_digits=10, decimal_places=2, verbose_name='Цена')
    units = models.CharField(null=False, blank=False, max_length=32, verbose_name='Единица измерения')

    def __str__(self):
        return '%s %s %s' % (self.price_list, self.product, self.price)

    class Meta:
        verbose_name = 'Позиция прайс-листа'
        verbose_name_plural = 'Позиции прайс-листов'


class Product(models.Model):
    title = models.CharField(max_length=64, null=False, blank=False, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    weight = models.IntegerField(null=False, blank=False, verbose_name='Вес (гр.)')
    image = models.ImageField(null=True, blank=True, upload_to='products_img/')

    def __str__(self):
        return '%s' % (self.title)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class TagAndProduct(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Продукт')
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Тег')

    def __str__(self):
        return '%s %s' % (self.product, self.tag)

    class Meta:
        verbose_name = 'Тег и продукт'
        verbose_name_plural = 'Теги и продукты'
        unique_together = ('product', 'tag')


class Tag(models.Model):
    title = models.CharField(max_length=64, null=False, blank=False, verbose_name='Наименование для тега')
    title_for_topic = models.CharField(max_length=64, null=True, blank=True, verbose_name='Наименование')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    board_image = models.ImageField(null=True, blank=True, upload_to='tags_img/board')
    icon_image = models.ImageField(null=True, blank=True, upload_to='tags_img/icon')

    def __str__(self):
        return '%s' % (self.title)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Customer(User):
    phone_number = models.CharField(max_length=18, null=False, blank=False, verbose_name='Номер телефона')

    class Meta:
        verbose_name = 'Покупатель'
        verbose_name_plural = 'Покупатели'


class Employee(User):
    date_of_employment = models.DateField(null=False, blank=False, verbose_name='Дата приема на работу')
    date_of_dismissal = models.DateField(null=True, blank=True, verbose_name='Дата увольнения')
    employees_position = models.CharField(max_length=32, null=True, blank=True, verbose_name='Должность')

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

pages/templates/objects/card.html
{% block content %}
    <div class="row row-cols-lg-6 row-cols-md-3 row-cols-sm-2">
        {% for item in orders %}
            <div class="col" style="margin-top: 2em">
                <div class="card custom-card" onclick="location.href='/';">
                    <div style="height: 50%;">
                        <img src="{{ MEDIA_URL }}{{ item.image.url }}" class="card-img-top">
                    </div>
                    <div class="card-body custom-card-body">
                        <div style="height: 6%; font-size: 0.9em">
                            {% for tagandproduct in item.tagandproduct_set.all|slice:":2" %}
                                <a class="badge rounded-pill text-bg custom-tag" style="height: 2.2em;" href="{% url 'topic' tagandproduct.tag.id %}">
                                        <img src="{{ MEDIA_URL }}{{ tagandproduct.tag.icon_image.url }}" class="tag-img">
                                        {{ tagandproduct.tag.title }}
                                    </a>
                            {% endfor %}
                        </div>
                        <div style="height: 60%">
                            <h5 style="margin-bottom: 0.2em; margin-top: 1em">{{ item.title }}</h5>
                            {{ item.weight }}г
                            <div style="color: #b59285; font-weight: bold">{{ item.price }}руб</div>
                        </div>
                        <div class="text-end" style="height: 40%">
                            {% if request.user.is_authenticated %}
                                <a class="btn custom-button-pill" href="{% url 'add_to_cart' item.id %}">В корзину</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <style>
        .custom-card-body {
            height: 50%;
            padding: 0.8em;
            margin-top: -10%;
            border-radius: 2em;
            background: #fdefd6;
        }

        .custom-card {
            height: auto;
            border-radius: 2em;
            aspect-ratio: 3/4;
            background: #fdefd6;
            border-style: none;
            box-shadow: 10px 20px 25px rgba(0, 0, 0, 0.4);
        }

        .card-img-top {
            width: 100%; /* заполнение ширины оболочки */
            height: 100%; /* заполнение высоты оболочки */
            object-fit: cover;
            border-top-left-radius: 2em;
            border-top-right-radius: 2em;
        }

        .tag-img {
            width: 1.2em; /* заполнение ширины оболочки */
            height: 1.2em;
        }

        .custom-tag {
            border-style: solid;
            border-width: .2em;
            border-color: #886b39;
            background: #fbd492;
            color: #886b39;
            margin-right: 0.1em;
            text-decoration: none;
        }
    </style>
{% endblock content %}

pages/templates/objects/carusel.html
{% block content %}
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            {% for item in topics %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}" style="aspect-ratio: 4/1;" location.href='/';>
                    <img src="media/{{ MEDIA_URL }}{{ item.board_image}}" class="d-block w-100 img-in-topic">
                    <div class="carousel-caption d-none d-md-block for-text-in-topic">
                        <h1 class="text-in-topic">{{ item.title_for_topic }}</h1>
                    </div>
                </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <style>
        .img-in-topic{
            width: 100%; /* заполнение ширины оболочки */
            height: 100%; /* заполнение высоты оболочки */
            object-fit: cover;
            border-radius: 2rem;
        }
        .text-in-topic {
            background-color: transparent; /* Прозрачный фон */
            mix-blend-mode: difference; /* Инверсия цвета */
            color: #f9c468; /* Цвет текста */
        }

        .for-text-in-topic {
            display: inline-block;
            padding: 0px;
            min-width: 10px;
            background-color: transparent;
            transition: background-color 0.3s ease-in-out;
            backdrop-filter: blur(10px);
            border-radius: 1000px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.4);
        }
    </style>
{% endblock content %}